# Minimal workflow file for repositories using reusable workflow
#
# Two-Tier Review System:
#   - Automatic security review on PR open/update (fast, Haiku)
#   - Full comprehensive review via "/review" comment (thorough, Sonnet)
#
# Note: Secrets (REVIEWER_TOKEN, ANTHROPIC_API_KEY, GLU_APP_ID, GLU_PRIVATE_KEY)
#       are configured at the organization level

name: Glu Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  review:
    if: |
      github.event_name == 'pull_request' ||
      (github.event.issue.pull_request && contains(github.event.comment.body, '/review'))
    uses: whitespaceenergy/internal-whitespace-glu-reviewer/.github/workflows/glu-review-reusable.yml@main
    secrets: inherit
